import type { TemplateDef } from './types';

/**
 * Connectivity reporting templates for the NCA demo library. These cover the returns that internet
 * and mobile operators file on broadband uptake, physical and spectrum infrastructure, and security
 * incidents. Section and field order follow array position.
 */
export const connectivityTemplates: TemplateDef[] = [
  {
    name: 'Internet & Broadband Return',
    description:
      'Quarterly and annual return on fixed and mobile broadband subscribers, international bandwidth, capacity use and retail pricing.',
    sections: [
      {
        key: 'fixed_broadband_subscribers',
        title: 'Fixed Broadband Subscribers',
        description:
          'Active fixed broadband connections at the end of the period, split by access technology.',
        applicableEntityTypes: ['ISP', 'MNO'],
        frequency: 'QUARTERLY_AND_ANNUAL',
        fields: [
          {
            key: 'fibre_subscribers',
            label: 'Fibre subscribers',
            dataType: 'INTEGER',
            description: 'Connections delivered over fibre to the home or premises.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'dsl_subscribers',
            label: 'DSL subscribers',
            dataType: 'INTEGER',
            description: 'Connections delivered over copper DSL lines.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'fixed_wireless_subscribers',
            label: 'Fixed wireless subscribers',
            dataType: 'INTEGER',
            description: 'Connections delivered over fixed wireless access.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'total_fixed_subscribers',
            label: 'Total fixed broadband subscribers',
            dataType: 'INTEGER',
            description: 'All active fixed broadband connections across every technology.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'primary_access_technology',
            label: 'Primary access technology',
            dataType: 'REFERENCE',
            description:
              'The access technology that carries the largest share of fixed subscribers.',
            referenceCategory: 'FIXED_ACCESS_TYPE',
            allowsOther: true,
          },
          {
            key: 'offers_symmetric_plans',
            label: 'Offers symmetric plans',
            dataType: 'BOOLEAN',
            description: 'Whether any retail plan offers equal upload and download speeds.',
          },
        ],
      },
      {
        key: 'mobile_broadband',
        title: 'Mobile Broadband',
        description: 'Mobile data subscribers and traffic carried over the period.',
        applicableEntityTypes: ['ISP', 'MNO'],
        frequency: 'QUARTERLY_AND_ANNUAL',
        fields: [
          {
            key: 'mobile_broadband_subscribers',
            label: 'Mobile broadband subscribers',
            dataType: 'INTEGER',
            description: 'Subscribers with an active mobile data plan at the end of the period.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'active_data_users',
            label: 'Active data users',
            dataType: 'INTEGER',
            description: 'Subscribers who used mobile data at least once during the period.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'new_activations',
            label: 'New data activations',
            dataType: 'INTEGER',
            description: 'Mobile data plans activated during the period.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'data_traffic_terabytes',
            label: 'Mobile data traffic',
            dataType: 'DECIMAL',
            description: 'Total mobile data carried during the period.',
            unit: 'TB',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'avg_data_usage_per_user',
            label: 'Average data use per user',
            dataType: 'DECIMAL',
            description: 'Average monthly data used by an active data user.',
            unit: 'GB',
            decimals: 1,
            minValue: 0,
          },
        ],
      },
      {
        key: 'bandwidth_capacity',
        title: 'Bandwidth & Capacity',
        description: 'International and domestic bandwidth held and how much of it is in use.',
        applicableEntityTypes: ['ISP', 'MNO'],
        frequency: 'QUARTERLY_AND_ANNUAL',
        fields: [
          {
            key: 'international_bandwidth',
            label: 'International bandwidth',
            dataType: 'INTEGER',
            description:
              'Total contracted international internet bandwidth at the end of the period.',
            unit: 'Mbps',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'domestic_bandwidth',
            label: 'Domestic bandwidth',
            dataType: 'INTEGER',
            description: 'Bandwidth carried over domestic links and exchanges.',
            unit: 'Mbps',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'capacity_utilisation',
            label: 'Capacity utilisation',
            dataType: 'PERCENTAGE',
            description: 'Average share of international bandwidth in use during the period.',
            unit: '%',
            isMandatory: true,
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'peak_utilisation',
            label: 'Peak utilisation',
            dataType: 'PERCENTAGE',
            description: 'Highest share of international bandwidth in use at busy hour.',
            unit: '%',
            minValue: 0,
            maxValue: 100,
          },
        ],
      },
      {
        key: 'pricing_snapshot',
        title: 'Pricing Snapshot',
        description: 'Retail broadband prices in effect at the end of the period.',
        applicableEntityTypes: ['ISP', 'MNO'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'entry_broadband_price',
            label: 'Entry broadband price',
            dataType: 'MONETARY',
            description: 'Monthly price of the cheapest advertised broadband plan.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            minValue: 0,
          },
          {
            key: 'avg_monthly_price',
            label: 'Average monthly price',
            dataType: 'MONETARY',
            description: 'Average monthly price paid across the retail broadband base.',
            unit: 'SSP',
            decimals: 2,
            minValue: 0,
          },
          {
            key: 'price_effective_date',
            label: 'Price effective date',
            dataType: 'DATE',
            description: 'Date the current price list took effect.',
          },
          {
            key: 'pricing_notes',
            label: 'Pricing notes',
            dataType: 'TEXTAREA',
            description:
              'Any promotions, bundling or fair use conditions that affect the prices reported.',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Fixed subscribers by technology must add up to the total',
        config: {
          operands: ['fibre_subscribers', 'dsl_subscribers', 'fixed_wireless_subscribers'],
          total: 'total_fixed_subscribers',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Active data users cannot exceed mobile broadband subscribers',
        config: {
          left: 'active_data_users',
          right: 'mobile_broadband_subscribers',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Average utilisation cannot exceed peak utilisation',
        config: {
          left: 'capacity_utilisation',
          right: 'peak_utilisation',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Large swing in capacity utilisation since last period',
        config: {
          field: 'capacity_utilisation',
          thresholdPercent: 25,
        },
      },
    ],
  },
  {
    name: 'Infrastructure & Spectrum Return',
    description:
      'Return on network sites and towers, site power, spectrum holdings and transmission backhaul.',
    sections: [
      {
        key: 'sites_towers',
        title: 'Sites & Towers',
        description: 'Network sites at the end of the period and how many are live.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY_AND_ANNUAL',
        fields: [
          {
            key: 'total_sites',
            label: 'Total sites',
            dataType: 'INTEGER',
            description: 'All network sites held at the end of the period, whether live or not.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'on_air_sites',
            label: 'On-air sites',
            dataType: 'INTEGER',
            description: 'Sites carrying live traffic at the end of the period.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'shared_sites',
            label: 'Shared sites',
            dataType: 'INTEGER',
            description:
              'Sites shared with another operator through colocation or an infrastructure deal.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'new_sites_built',
            label: 'New sites built',
            dataType: 'INTEGER',
            description: 'Sites brought into service during the period.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'geographic_area',
            label: 'Predominant coverage area',
            dataType: 'REFERENCE',
            description: 'The area type where most sites are located.',
            referenceCategory: 'GEO_CLASSIFICATION',
          },
        ],
      },
      {
        key: 'power',
        title: 'Power',
        description: 'How network sites are powered over an average day.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'grid_power_hours',
            label: 'Grid power hours',
            dataType: 'DECIMAL',
            description: 'Average hours per day a site runs on grid power.',
            unit: 'hours',
            decimals: 1,
            minValue: 0,
            maxValue: 24,
          },
          {
            key: 'solar_power_hours',
            label: 'Solar power hours',
            dataType: 'DECIMAL',
            description: 'Average hours per day a site runs on solar power.',
            unit: 'hours',
            decimals: 1,
            minValue: 0,
            maxValue: 24,
          },
          {
            key: 'generator_hours',
            label: 'Generator hours',
            dataType: 'DECIMAL',
            description: 'Average hours per day a site runs on a diesel or petrol generator.',
            unit: 'hours',
            decimals: 1,
            minValue: 0,
            maxValue: 24,
          },
          {
            key: 'primary_energy_source',
            label: 'Primary energy source',
            dataType: 'REFERENCE',
            description: 'The energy source that powers most sites for most of the day.',
            isMandatory: true,
            referenceCategory: 'ENERGY_GENERATION_TYPE',
            allowsOther: true,
          },
          {
            key: 'has_battery_backup',
            label: 'Has battery backup',
            dataType: 'BOOLEAN',
            description: 'Whether sites carry battery backup for use during power gaps.',
          },
          {
            key: 'energy_storage_type',
            label: 'Energy storage type',
            dataType: 'REFERENCE',
            description: 'The type of energy storage used where battery backup is present.',
            referenceCategory: 'ENERGY_STORAGE_TYPE',
            allowsOther: true,
          },
        ],
      },
      {
        key: 'spectrum_holdings',
        title: 'Spectrum Holdings',
        description: 'Spectrum assigned to the operator and how much is carrying traffic.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'spectrum_band',
            label: 'Spectrum band',
            dataType: 'REFERENCE',
            description: 'The frequency band this holding relates to.',
            isMandatory: true,
            referenceCategory: 'SPECTRUM_BAND',
          },
          {
            key: 'mhz_assigned',
            label: 'Spectrum assigned',
            dataType: 'DECIMAL',
            description: 'Total spectrum assigned to the operator in this band.',
            unit: 'MHz',
            decimals: 1,
            isMandatory: true,
            minValue: 0,
          },
          {
            key: 'mhz_in_use',
            label: 'Spectrum in use',
            dataType: 'DECIMAL',
            description: 'Assigned spectrum that is carrying live traffic.',
            unit: 'MHz',
            decimals: 1,
            minValue: 0,
          },
          {
            key: 'licence_expiry_date',
            label: 'Licence expiry date',
            dataType: 'DATE',
            description: 'Date the spectrum licence for this band expires.',
          },
          {
            key: 'spectrum_fee',
            label: 'Annual spectrum fee',
            dataType: 'MONETARY',
            description: 'Annual fee paid for the spectrum held in this band.',
            unit: 'SSP',
            decimals: 2,
            minValue: 0,
          },
        ],
      },
      {
        key: 'transmission',
        title: 'Transmission',
        description: 'Backhaul that connects sites to the core network.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY_AND_ANNUAL',
        fields: [
          {
            key: 'fibre_backhaul_km',
            label: 'Fibre backhaul',
            dataType: 'INTEGER',
            description: 'Length of fibre backhaul in service at the end of the period.',
            unit: 'km',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'microwave_links',
            label: 'Microwave links',
            dataType: 'INTEGER',
            description: 'Number of microwave backhaul links in service.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'backhaul_utilisation',
            label: 'Backhaul utilisation',
            dataType: 'PERCENTAGE',
            description: 'Average share of backhaul capacity in use during the period.',
            unit: '%',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'transmission_notes',
            label: 'Transmission notes',
            dataType: 'TEXTAREA',
            description: 'Any planned upgrades or constraints affecting the backhaul reported.',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'On-air sites cannot exceed total sites',
        config: {
          left: 'on_air_sites',
          right: 'total_sites',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Shared sites cannot exceed total sites',
        config: {
          left: 'shared_sites',
          right: 'total_sites',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Spectrum in use cannot exceed spectrum assigned',
        config: {
          left: 'mhz_in_use',
          right: 'mhz_assigned',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Large change in total sites since last period',
        config: {
          field: 'total_sites',
          thresholdPercent: 20,
        },
      },
    ],
  },
  {
    name: 'Cybersecurity & Incident Return',
    description:
      'Quarterly return on security incidents, service downtime and data protection breaches.',
    sections: [
      {
        key: 'security_incidents',
        title: 'Security Incidents',
        description: 'Security incidents raised and closed during the period.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'incidents_reported',
            label: 'Incidents reported',
            dataType: 'INTEGER',
            description: 'Security incidents raised during the period.',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'incidents_resolved',
            label: 'Incidents resolved',
            dataType: 'INTEGER',
            description: 'Incidents closed during the period, including ones raised earlier.',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'incidents_pending',
            label: 'Incidents pending',
            dataType: 'INTEGER',
            description: 'Incidents still open at the end of the period.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'critical_severity_incidents',
            label: 'Critical severity incidents',
            dataType: 'INTEGER',
            description: 'Reported incidents rated critical severity.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'highest_severity_level',
            label: 'Highest severity level',
            dataType: 'TEXT',
            description:
              'Severity of the most serious incident in the period, for example low, medium, high or critical.',
          },
          {
            key: 'avg_resolution_hours',
            label: 'Average resolution time',
            dataType: 'DECIMAL',
            description: 'Average time taken to close an incident.',
            unit: 'hours',
            decimals: 1,
            minValue: 0,
          },
        ],
      },
      {
        key: 'service_downtime',
        title: 'Service Downtime',
        description: 'Service outages recorded during the period.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'outage_count',
            label: 'Outage count',
            dataType: 'INTEGER',
            description: 'Number of separate service outages during the period.',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_downtime_minutes',
            label: 'Total downtime',
            dataType: 'INTEGER',
            description: 'Total minutes of service downtime across all outages.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'planned_downtime_minutes',
            label: 'Planned downtime',
            dataType: 'INTEGER',
            description: 'Downtime that was scheduled in advance for maintenance.',
            unit: 'minutes',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'longest_outage_minutes',
            label: 'Longest single outage',
            dataType: 'INTEGER',
            description: 'Duration of the single longest outage in the period.',
            unit: 'minutes',
            minValue: 0,
          },
          {
            key: 'service_availability',
            label: 'Service availability',
            dataType: 'PERCENTAGE',
            description: 'Share of the period the service was available to users.',
            unit: '%',
            minValue: 0,
            maxValue: 100,
          },
        ],
      },
      {
        key: 'data_protection',
        title: 'Data Protection',
        description: 'Personal data breaches recorded during the period.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'data_breaches',
            label: 'Data breaches',
            dataType: 'INTEGER',
            description: 'Confirmed personal data breaches during the period.',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'users_affected',
            label: 'Users affected',
            dataType: 'INTEGER',
            description: 'Number of users whose data was involved in a breach.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'breach_notification_sent',
            label: 'Breach notification sent',
            dataType: 'BOOLEAN',
            description: 'Whether affected users and the Authority were notified.',
          },
          {
            key: 'last_breach_date',
            label: 'Date of most recent breach',
            dataType: 'DATE',
            description: 'Date the most recent breach in the period was confirmed.',
          },
          {
            key: 'remediation_summary',
            label: 'Remediation summary',
            dataType: 'TEXTAREA',
            description: 'Steps taken to contain the breaches and stop them happening again.',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Resolved incidents cannot exceed reported incidents',
        config: {
          left: 'incidents_resolved',
          right: 'incidents_reported',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Critical incidents cannot exceed reported incidents',
        config: {
          left: 'critical_severity_incidents',
          right: 'incidents_reported',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Planned downtime cannot exceed total downtime',
        config: {
          left: 'planned_downtime_minutes',
          right: 'total_downtime_minutes',
        },
      },
      {
        type: 'NONZERO_REQUIRES',
        severity: 'SOFT',
        label: 'Report users affected when a breach is recorded',
        config: {
          when: 'data_breaches',
          require: 'users_affected',
        },
      },
    ],
  },
];
