import type { TemplateDef } from './types';

/**
 * Financial and investment reporting templates for the NCA demo library.
 *
 * These cover the money side of the returns licensees file each year: how much they earned and
 * spent, how their mobile money operations moved, and what they invested in network and capital.
 * The seed runner publishes each template and checks every rule against the numeric fields below.
 */
export const financialTemplates: TemplateDef[] = [
  {
    name: 'Financial Performance Return (Annual)',
    description:
      'Yearly summary of revenue, costs, profitability, and the taxes and fees a licensee paid. All figures are in South Sudanese Pounds for the reporting financial year.',
    sections: [
      {
        key: 'revenue_by_stream',
        title: 'Revenue by stream',
        description: 'Gross revenue earned in the year, split by the service it came from.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO', 'VENDOR', 'OTHER'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'voice_revenue',
            label: 'Voice revenue',
            dataType: 'MONETARY',
            description: 'Revenue from voice calls, including local, national, and international.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'data_revenue',
            label: 'Data revenue',
            dataType: 'MONETARY',
            description: 'Revenue from mobile and fixed data services.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'sms_revenue',
            label: 'SMS revenue',
            dataType: 'MONETARY',
            description: 'Revenue from person to person and bulk messaging.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'other_revenue',
            label: 'Other revenue',
            dataType: 'MONETARY',
            description: 'Any remaining revenue that does not fall under voice, data, or SMS.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_revenue',
            label: 'Total revenue',
            dataType: 'MONETARY',
            description: 'Sum of all revenue streams for the year.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'costs',
        title: 'Costs',
        description:
          'Operating and staff costs, plus what was paid to other operators to carry traffic.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO', 'VENDOR', 'OTHER'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'operating_expenditure',
            label: 'Operating expenditure',
            dataType: 'MONETARY',
            description: 'Total running costs for the year, excluding staff and interconnection.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'staff_cost',
            label: 'Staff cost',
            dataType: 'MONETARY',
            description: 'Salaries, benefits, and other employment costs.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'interconnection_cost',
            label: 'Interconnection cost',
            dataType: 'MONETARY',
            description: 'Fees paid to other operators for terminating or carrying traffic.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_costs',
            label: 'Total costs',
            dataType: 'MONETARY',
            description: 'Sum of operating, staff, and interconnection costs.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'profitability',
        title: 'Profitability',
        description: 'Earnings before and after the usual deductions.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO', 'VENDOR', 'OTHER'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'ebitda',
            label: 'EBITDA',
            dataType: 'MONETARY',
            description: 'Earnings before interest, tax, depreciation, and amortisation.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
          },
          {
            key: 'net_profit',
            label: 'Net profit',
            dataType: 'MONETARY',
            description: 'Profit after all costs, tax, and finance charges. May be negative.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
          },
          {
            key: 'ebitda_margin',
            label: 'EBITDA margin',
            dataType: 'PERCENTAGE',
            description: 'EBITDA as a share of total revenue.',
            unit: '%',
            decimals: 1,
            flowOrStock: 'NONE',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'accounts_audited',
            label: 'Accounts audited',
            dataType: 'BOOLEAN',
            description: 'Tick if these figures come from audited financial statements.',
            flowOrStock: 'NONE',
          },
        ],
      },
      {
        key: 'taxes_and_fees',
        title: 'Taxes and fees',
        description: 'Amounts paid to government and to the Authority during the year.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO', 'VENDOR', 'OTHER'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'corporate_tax',
            label: 'Corporate tax',
            dataType: 'MONETARY',
            description: 'Income tax paid on company profits.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'regulatory_fees',
            label: 'Regulatory fees',
            dataType: 'MONETARY',
            description: 'Annual licence and regulatory fees paid to the Authority.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'spectrum_fees',
            label: 'Spectrum fees',
            dataType: 'MONETARY',
            description: 'Fees paid for the use of assigned frequency spectrum.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'universal_service_fund_contribution',
            label: 'Universal service fund contribution',
            dataType: 'MONETARY',
            description: 'Contribution to the universal service and access fund.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'financial_year_end',
            label: 'Financial year end',
            dataType: 'DATE',
            description: 'The last day of the financial year these figures cover.',
            flowOrStock: 'NONE',
          },
          {
            key: 'tax_notes',
            label: 'Notes',
            dataType: 'TEXTAREA',
            description: 'Anything the Authority should know when reading these figures.',
            flowOrStock: 'NONE',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Revenue streams must add up to total revenue',
        config: {
          operands: ['voice_revenue', 'data_revenue', 'sms_revenue', 'other_revenue'],
          total: 'total_revenue',
          tolerancePercent: 0.5,
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Interconnection cost cannot exceed total costs',
        config: {
          left: 'interconnection_cost',
          right: 'total_costs',
        },
      },
      {
        type: 'NONZERO_REQUIRES',
        severity: 'SOFT',
        label: 'Revenue reported but no costs recorded',
        config: {
          when: 'total_revenue',
          require: 'total_costs',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Large year on year change in total revenue',
        config: {
          field: 'total_revenue',
          thresholdPercent: 40,
        },
      },
    ],
  },
  {
    name: 'Mobile Money Operations Return',
    description:
      'Monthly return for mobile money operators covering customer accounts, the float held in trust, transaction activity, and the agent network.',
    sections: [
      {
        key: 'accounts',
        title: 'Accounts',
        description: 'Customer wallet accounts at the end of the month.',
        applicableEntityTypes: ['MMO'],
        frequency: 'MONTHLY',
        fields: [
          {
            key: 'registered_accounts',
            label: 'Registered accounts',
            dataType: 'INTEGER',
            description: 'Total customer accounts on the books at month end.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'active_90_day_users',
            label: 'Active users (90 days)',
            dataType: 'INTEGER',
            description: 'Accounts with at least one transaction in the last 90 days.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'new_accounts_opened',
            label: 'New accounts opened',
            dataType: 'INTEGER',
            description: 'Accounts opened during the month.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'dormant_accounts',
            label: 'Dormant accounts',
            dataType: 'INTEGER',
            description: 'Accounts with no activity for more than 90 days.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
        ],
      },
      {
        key: 'float_and_trust',
        title: 'Float and trust',
        description: 'The money held to back the e-money in circulation.',
        applicableEntityTypes: ['MMO'],
        frequency: 'MONTHLY',
        fields: [
          {
            key: 'float_trust_balance',
            label: 'Float and trust balance',
            dataType: 'MONETARY',
            description: 'Cash held in trust accounts to back e-money at month end.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'e_money_issued',
            label: 'E-money issued',
            dataType: 'MONETARY',
            description: 'Total value of e-money in circulation at month end.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'number_of_trust_accounts',
            label: 'Number of trust accounts',
            dataType: 'INTEGER',
            description: 'Count of bank trust accounts holding the float.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'trust_reconciled',
            label: 'Trust reconciled',
            dataType: 'BOOLEAN',
            description: 'Tick if the trust balance was reconciled against e-money issued.',
            flowOrStock: 'NONE',
          },
          {
            key: 'balance_date',
            label: 'Balance date',
            dataType: 'DATE',
            description: 'Date the balances above were taken.',
            flowOrStock: 'NONE',
          },
        ],
      },
      {
        key: 'transactions',
        title: 'Transactions',
        description: 'Value and count of transactions processed during the month.',
        applicableEntityTypes: ['MMO'],
        frequency: 'MONTHLY',
        fields: [
          {
            key: 'cash_in_value',
            label: 'Cash-in value',
            dataType: 'MONETARY',
            description: 'Total value of deposits into wallets.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'cash_out_value',
            label: 'Cash-out value',
            dataType: 'MONETARY',
            description: 'Total value of withdrawals from wallets.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'p2p_transfer_value',
            label: 'P2P transfer value',
            dataType: 'MONETARY',
            description: 'Total value of person to person transfers.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_transaction_value',
            label: 'Total transaction value',
            dataType: 'MONETARY',
            description: 'Sum of cash-in, cash-out, and P2P transfer value.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_transaction_count',
            label: 'Total transaction count',
            dataType: 'INTEGER',
            description: 'Number of transactions of all types during the month.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'agents',
        title: 'Agents',
        description: 'The agent network that handles cash-in and cash-out for customers.',
        applicableEntityTypes: ['MMO'],
        frequency: 'MONTHLY',
        fields: [
          {
            key: 'registered_agents',
            label: 'Registered agents',
            dataType: 'INTEGER',
            description: 'Total agents on the books at month end.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'active_agents',
            label: 'Active agents',
            dataType: 'INTEGER',
            description: 'Agents that processed at least one transaction in the month.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'new_agents_recruited',
            label: 'New agents recruited',
            dataType: 'INTEGER',
            description: 'Agents signed up during the month.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'agent_commission_paid',
            label: 'Agent commission paid',
            dataType: 'MONETARY',
            description: 'Total commission paid to agents during the month.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
    ],
    rules: [
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Active users cannot exceed registered accounts',
        config: {
          left: 'active_90_day_users',
          right: 'registered_accounts',
        },
      },
      {
        type: 'FLOAT_RECONCILE',
        severity: 'HARD',
        label: 'Float and trust balance must back the e-money issued',
        config: {
          balance: 'float_trust_balance',
          backing: 'e_money_issued',
        },
      },
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Cash-in, cash-out, and P2P must add up to total transaction value',
        config: {
          operands: ['cash_in_value', 'cash_out_value', 'p2p_transfer_value'],
          total: 'total_transaction_value',
          tolerancePercent: 0.5,
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'SOFT',
        label: 'Active agents cannot exceed registered agents',
        config: {
          left: 'active_agents',
          right: 'registered_agents',
        },
      },
    ],
  },
  {
    name: 'Investment & Capital Expenditure Return (Annual)',
    description:
      'Yearly return on capital investment: what was spent by category, foreign direct investment received, and money put into extending the network.',
    sections: [
      {
        key: 'capex_by_category',
        title: 'Capex by category',
        description: 'Capital spending in the year, split by what it was spent on.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'network_capex',
            label: 'Network capex',
            dataType: 'MONETARY',
            description: 'Spending on network equipment, sites, and transmission.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'it_systems_capex',
            label: 'IT systems capex',
            dataType: 'MONETARY',
            description: 'Spending on billing, IT, and back office systems.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'other_capex',
            label: 'Other capex',
            dataType: 'MONETARY',
            description: 'Capital spending that does not fall under network or IT systems.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_capex',
            label: 'Total capex',
            dataType: 'MONETARY',
            description: 'Sum of all capital spending for the year.',
            unit: 'SSP',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'foreign_direct_investment',
        title: 'Foreign direct investment',
        description: 'Investment received from outside South Sudan during the year.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'fdi_inflow',
            label: 'FDI inflow',
            dataType: 'MONETARY',
            description: 'Total foreign direct investment received in the year.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'foreign_ownership_share',
            label: 'Foreign ownership share',
            dataType: 'PERCENTAGE',
            description: 'Share of the company held by foreign investors at year end.',
            unit: '%',
            decimals: 1,
            flowOrStock: 'NONE',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'has_foreign_shareholder',
            label: 'Has foreign shareholder',
            dataType: 'BOOLEAN',
            description: 'Tick if any shareholder is based outside South Sudan.',
            flowOrStock: 'NONE',
          },
          {
            key: 'main_investor_country',
            label: 'Main investor country',
            dataType: 'TEXT',
            description: 'Country of the largest foreign investor, if any.',
            flowOrStock: 'NONE',
          },
        ],
      },
      {
        key: 'network_rollout',
        title: 'Network rollout',
        description: 'Investment in extending coverage and building new sites.',
        applicableEntityTypes: ['MNO', 'ISP', 'MMO'],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'rollout_capex',
            label: 'Rollout capex',
            dataType: 'MONETARY',
            description: 'Capital spent specifically on extending network coverage.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'new_sites_built',
            label: 'New sites built',
            dataType: 'INTEGER',
            description: 'Number of new base station sites brought into service.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'population_coverage',
            label: 'Population coverage',
            dataType: 'PERCENTAGE',
            description: 'Share of the population covered by the network at year end.',
            unit: '%',
            decimals: 1,
            flowOrStock: 'NONE',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'rollout_completion_date',
            label: 'Rollout completion date',
            dataType: 'DATE',
            description: 'Date the planned rollout for the year was completed.',
            flowOrStock: 'NONE',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Capex categories must add up to total capex',
        config: {
          operands: ['network_capex', 'it_systems_capex', 'other_capex'],
          total: 'total_capex',
          tolerancePercent: 0.5,
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Rollout capex cannot exceed total capex',
        config: {
          left: 'rollout_capex',
          right: 'total_capex',
        },
      },
      {
        type: 'NONZERO_REQUIRES',
        severity: 'SOFT',
        label: 'New sites built but no rollout capex recorded',
        config: {
          when: 'new_sites_built',
          require: 'rollout_capex',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Large year on year change in total capex',
        config: {
          field: 'total_capex',
          thresholdPercent: 50,
        },
      },
    ],
  },
];
