import type { TemplateDef } from './types';

const ALL_ENTITY_TYPES = ['MNO', 'ISP', 'MMO', 'VENDOR', 'OTHER'] as const;

/**
 * Governance and consumer-facing returns: complaints handling, workforce localization,
 * universal access, and annual licence compliance. These templates lean on boolean, date,
 * textarea, and reference fields alongside the usual counts and money.
 */
export const governanceTemplates: TemplateDef[] = [
  {
    name: 'Consumer Affairs & Complaints Return',
    description:
      'Quarterly return covering complaints received and resolved, how long resolutions take, and any refunds or compensation paid to consumers.',
    sections: [
      {
        key: 'complaints_handling',
        title: 'Complaints handling',
        description:
          'Volumes of complaints received, resolved, and still open during the period, broken down by service.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'complaints_received',
            label: 'Complaints received',
            dataType: 'INTEGER',
            description: 'Total complaints received from consumers during the period.',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'complaints_resolved',
            label: 'Complaints resolved',
            dataType: 'INTEGER',
            description: 'Complaints closed to the consumer’s satisfaction during the period.',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'complaints_pending',
            label: 'Complaints pending',
            dataType: 'INTEGER',
            description: 'Complaints still open at the end of the period.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'complaints_escalated',
            label: 'Complaints escalated to the Authority',
            dataType: 'INTEGER',
            description:
              'Complaints referred to the Authority because they could not be settled directly.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'complaints_by_category',
            label: 'Complaints by category',
            dataType: 'REFERENCE',
            description: 'Breakdown of complaints by the service they relate to.',
            referenceCategory: 'SERVICE_TYPE',
            allowsOther: true,
          },
        ],
      },
      {
        key: 'resolution_times',
        title: 'Resolution times',
        description: 'How quickly complaints were dealt with and how many met the service level.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'avg_resolution_days',
            label: 'Average resolution time (days)',
            dataType: 'DECIMAL',
            description: 'Average number of days taken to close a complaint.',
            isMandatory: true,
            decimals: 1,
            flowOrStock: 'NONE',
            minValue: 0,
          },
          {
            key: 'fastest_resolution_days',
            label: 'Fastest resolution time (days)',
            dataType: 'DECIMAL',
            description: 'Shortest time taken to close a complaint in the period.',
            decimals: 1,
            flowOrStock: 'NONE',
            minValue: 0,
          },
          {
            key: 'slowest_resolution_days',
            label: 'Slowest resolution time (days)',
            dataType: 'DECIMAL',
            description: 'Longest time taken to close a complaint in the period.',
            decimals: 1,
            flowOrStock: 'NONE',
            minValue: 0,
          },
          {
            key: 'complaints_within_sla',
            label: 'Complaints resolved within the service level',
            dataType: 'INTEGER',
            description: 'Complaints closed inside the agreed service level window.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'sla_compliance_pct',
            label: 'Service level compliance',
            dataType: 'PERCENTAGE',
            description: 'Share of complaints resolved within the agreed service level.',
            flowOrStock: 'NONE',
            minValue: 0,
            maxValue: 100,
          },
        ],
      },
      {
        key: 'refunds_compensation',
        title: 'Refunds and compensation',
        description: 'Money returned or paid to consumers as a result of complaints.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'refunds_issued',
            label: 'Number of refunds issued',
            dataType: 'INTEGER',
            description: 'Count of refunds paid to consumers during the period.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'refunds_paid',
            label: 'Refunds paid',
            dataType: 'MONETARY',
            description: 'Total value of refunds paid to consumers.',
            isMandatory: true,
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'compensation_paid',
            label: 'Compensation paid',
            dataType: 'MONETARY',
            description: 'Total value of compensation paid to consumers beyond refunds.',
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_redress_paid',
            label: 'Total redress paid',
            dataType: 'MONETARY',
            description: 'Refunds and compensation added together.',
            isMandatory: true,
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
    ],
    rules: [
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Complaints resolved cannot exceed complaints received',
        config: { left: 'complaints_resolved', right: 'complaints_received' },
      },
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Refunds plus compensation must equal total redress',
        config: {
          operands: ['refunds_paid', 'compensation_paid'],
          total: 'total_redress_paid',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Large swing in complaints received',
        config: { field: 'complaints_received', thresholdPercent: 40 },
      },
    ],
  },
  {
    name: 'Employment & Localization Return (Annual)',
    description:
      'Annual return on the size and make-up of the workforce, the split between national and expatriate staff, gender balance, and investment in training.',
    sections: [
      {
        key: 'workforce',
        title: 'Workforce',
        description:
          'Headcount at the end of the year, split between national and expatriate staff.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'national_staff',
            label: 'National staff',
            dataType: 'INTEGER',
            description: 'South Sudanese employees at the end of the year.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'expatriate_staff',
            label: 'Expatriate staff',
            dataType: 'INTEGER',
            description: 'Non-national employees at the end of the year.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'total_staff',
            label: 'Total staff',
            dataType: 'INTEGER',
            description: 'All employees at the end of the year.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'new_hires',
            label: 'New hires during the year',
            dataType: 'INTEGER',
            description: 'Staff recruited during the year.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'gender',
        title: 'Gender balance',
        description: 'Split of the workforce by gender and the share of women in management.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'female_staff',
            label: 'Female staff',
            dataType: 'INTEGER',
            description: 'Women employed at the end of the year.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'male_staff',
            label: 'Male staff',
            dataType: 'INTEGER',
            description: 'Men employed at the end of the year.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'women_in_management',
            label: 'Women in management roles',
            dataType: 'INTEGER',
            description: 'Female staff holding management positions.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'female_staff_pct',
            label: 'Share of female staff',
            dataType: 'PERCENTAGE',
            description: 'Women as a share of total staff.',
            flowOrStock: 'NONE',
            minValue: 0,
            maxValue: 100,
          },
        ],
      },
      {
        key: 'training_development',
        title: 'Training and development',
        description: 'Investment in developing staff and progress towards localization targets.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'staff_trained',
            label: 'Staff trained',
            dataType: 'INTEGER',
            description: 'Employees who completed at least one training programme during the year.',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'training_hours',
            label: 'Total training hours',
            dataType: 'INTEGER',
            description: 'Total hours of training delivered to staff during the year.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'training_spend',
            label: 'Training spend',
            dataType: 'MONETARY',
            description: 'Total spent on staff training during the year.',
            isMandatory: true,
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'localization_target_pct',
            label: 'Localization target',
            dataType: 'PERCENTAGE',
            description: 'Target share of national staff for the coming year.',
            flowOrStock: 'NONE',
            minValue: 0,
            maxValue: 100,
          },
        ],
      },
    ],
    rules: [
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'National and expatriate staff must add up to total staff',
        config: { operands: ['national_staff', 'expatriate_staff'], total: 'total_staff' },
      },
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Female and male staff must add up to total staff',
        config: { operands: ['female_staff', 'male_staff'], total: 'total_staff' },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'SOFT',
        label: 'Women in management cannot exceed female staff',
        config: { left: 'women_in_management', right: 'female_staff' },
      },
    ],
  },
  {
    name: 'Universal Access & Rural Coverage Return',
    description:
      'Return on progress extending networks into rural areas, connecting schools and health facilities, and keeping services affordable.',
    sections: [
      {
        key: 'rural_coverage',
        title: 'Rural coverage',
        description: 'Sites and population reached in rural areas.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'rural_sites',
            label: 'Rural sites in service',
            dataType: 'INTEGER',
            description: 'Network sites in service in rural areas at the end of the period.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'new_rural_sites',
            label: 'New rural sites added',
            dataType: 'INTEGER',
            description: 'Rural sites brought into service during the period.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'villages_covered',
            label: 'Villages covered',
            dataType: 'INTEGER',
            description: 'Rural villages with usable coverage at the end of the period.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'rural_population_covered_pct',
            label: 'Rural population covered',
            dataType: 'PERCENTAGE',
            description: 'Share of the rural population within coverage.',
            isMandatory: true,
            flowOrStock: 'NONE',
            minValue: 0,
            maxValue: 100,
          },
        ],
      },
      {
        key: 'access_programmes',
        title: 'Access programmes',
        description: 'Connections delivered to public institutions under access programmes.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'schools_connected',
            label: 'Schools connected',
            dataType: 'INTEGER',
            description: 'Schools with an active connection at the end of the period.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'health_facilities_connected',
            label: 'Health facilities connected',
            dataType: 'INTEGER',
            description: 'Health facilities with an active connection at the end of the period.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'public_wifi_hotspots',
            label: 'Public wifi hotspots',
            dataType: 'INTEGER',
            description: 'Public wifi hotspots in service at the end of the period.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'community_centres_connected',
            label: 'Community centres connected',
            dataType: 'INTEGER',
            description: 'Community centres with an active connection at the end of the period.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
        ],
      },
      {
        key: 'affordability',
        title: 'Affordability',
        description: 'Prices and subsidies that shape how affordable services are in rural areas.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'cheapest_data_bundle_price',
            label: 'Cheapest monthly data bundle',
            dataType: 'MONETARY',
            description: 'Price of the cheapest monthly data bundle on offer.',
            isMandatory: true,
            unit: 'SSP',
            flowOrStock: 'NONE',
            minValue: 0,
          },
          {
            key: 'avg_monthly_arpu',
            label: 'Average monthly revenue per user',
            dataType: 'MONETARY',
            description: 'Average revenue earned per active user each month.',
            unit: 'SSP',
            flowOrStock: 'NONE',
            minValue: 0,
          },
          {
            key: 'subsidised_connections',
            label: 'Subsidised connections',
            dataType: 'INTEGER',
            description: 'Connections provided at a subsidised rate during the period.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'affordability_index',
            label: 'Affordability index',
            dataType: 'DECIMAL',
            description: 'Cheapest data bundle as a share of average monthly income.',
            decimals: 2,
            flowOrStock: 'NONE',
            minValue: 0,
          },
        ],
      },
    ],
    rules: [
      {
        type: 'LESS_OR_EQUAL',
        severity: 'SOFT',
        label: 'New rural sites cannot exceed total rural sites',
        config: { left: 'new_rural_sites', right: 'rural_sites' },
      },
      {
        type: 'NONZERO_REQUIRES',
        severity: 'HARD',
        label: 'Villages covered requires rural sites in service',
        config: { when: 'villages_covered', require: 'rural_sites' },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Large swing in rural sites in service',
        config: { field: 'rural_sites', thresholdPercent: 30 },
      },
    ],
  },
  {
    name: 'Annual Licence Compliance Return',
    description:
      'Annual declaration confirming licence fees are paid, licence obligations are met, and regulatory fees are settled, with a signed statement from the licensee.',
    sections: [
      {
        key: 'licence_obligations',
        title: 'Licence and obligations',
        description: 'Confirmation that the licence fee is paid and licence obligations are met.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'licence_number',
            label: 'Licence number',
            dataType: 'TEXT',
            description: 'The licence this return relates to.',
            isMandatory: true,
          },
          {
            key: 'licence_fee_paid',
            label: 'Licence fee paid',
            dataType: 'MONETARY',
            description: 'Total licence fee paid to the Authority during the year.',
            isMandatory: true,
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'obligations_met',
            label: 'All licence obligations met',
            dataType: 'BOOLEAN',
            description: 'Confirm whether all licence obligations were met during the year.',
            isMandatory: true,
          },
          {
            key: 'compliance_date',
            label: 'Date obligations confirmed',
            dataType: 'DATE',
            description: 'Date on which compliance with the obligations was confirmed.',
            isMandatory: true,
          },
        ],
      },
      {
        key: 'regulatory_fees',
        title: 'Regulatory fees',
        description:
          'Spectrum, numbering, and universal service fund payments made during the year.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'spectrum_fees',
            label: 'Spectrum fees paid',
            dataType: 'MONETARY',
            description: 'Total spectrum fees paid during the year.',
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'usf_contribution',
            label: 'Universal service fund contribution',
            dataType: 'MONETARY',
            description: 'Contribution paid to the universal service fund during the year.',
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'numbering_fees',
            label: 'Numbering fees paid',
            dataType: 'MONETARY',
            description: 'Total numbering fees paid during the year.',
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_fees_paid',
            label: 'Total regulatory fees paid',
            dataType: 'MONETARY',
            description: 'Spectrum, universal service fund, and numbering fees added together.',
            isMandatory: true,
            unit: 'SSP',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'declarations',
        title: 'Declarations',
        description: 'Signed statement from the licensee and any notes on outstanding matters.',
        applicableEntityTypes: [...ALL_ENTITY_TYPES],
        frequency: 'ANNUAL',
        fields: [
          {
            key: 'authorised_signatory',
            label: 'Authorised signatory',
            dataType: 'TEXT',
            description: 'Name of the person signing this return on behalf of the licensee.',
            isMandatory: true,
          },
          {
            key: 'declaration_date',
            label: 'Declaration date',
            dataType: 'DATE',
            description: 'Date the declaration was signed.',
            isMandatory: true,
          },
          {
            key: 'declaration_notes',
            label: 'Declaration notes',
            dataType: 'TEXTAREA',
            description: 'Any notes the licensee wishes to add to this return.',
          },
          {
            key: 'outstanding_issues',
            label: 'Outstanding compliance issues',
            dataType: 'TEXTAREA',
            description: 'Describe any obligations not yet met and the plan to put them right.',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Spectrum, universal service, and numbering fees must add up to total fees',
        config: {
          operands: ['spectrum_fees', 'usf_contribution', 'numbering_fees'],
          total: 'total_fees_paid',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Large swing in licence fee paid',
        config: { field: 'licence_fee_paid', thresholdPercent: 50 },
      },
    ],
  },
];
