import type { TemplateDef } from './types';

/**
 * Telecom reporting templates for the demo library. These mirror the periodic returns the National
 * Communications Authority collects from licensed mobile and internet operators: a broad quarterly
 * operator return, a voice and interconnection return, and a network quality of service return.
 */
export const telecomTemplates: TemplateDef[] = [
  {
    name: 'Mobile Network Operator Quarterly Return',
    description:
      'Quarterly return for mobile network operators covering the subscriber base, network coverage, ' +
      'traffic and usage, and a short quality snapshot for the reporting period.',
    sections: [
      {
        key: 'subscribers',
        title: 'Subscribers',
        description: 'Subscriber numbers as at the last day of the quarter, split by payment type.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'prepaid_subscribers',
            label: 'Prepaid subscribers',
            dataType: 'INTEGER',
            description: 'Prepaid SIMs registered at the end of the quarter.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'postpaid_subscribers',
            label: 'Postpaid subscribers',
            dataType: 'INTEGER',
            description: 'Postpaid accounts active at the end of the quarter.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'total_subscribers',
            label: 'Total subscribers',
            dataType: 'INTEGER',
            description: 'All registered subscribers, prepaid and postpaid together.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'active_subscribers',
            label: 'Active subscribers in the last 90 days',
            dataType: 'INTEGER',
            description: 'Subscribers who made or received a chargeable event in the last 90 days.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'reporting_period_end',
            label: 'Date the figures were taken',
            dataType: 'DATE',
            description:
              'The day the subscriber counts were pulled, normally the last day of the quarter.',
            isMandatory: true,
          },
        ],
      },
      {
        key: 'network_coverage',
        title: 'Network coverage',
        description: 'Population coverage and the site footprint at the end of the quarter.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'pop_covered_urban',
            label: 'Urban population covered',
            dataType: 'PERCENTAGE',
            description: 'Share of the urban population within your network coverage.',
            unit: '%',
            isMandatory: true,
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'pop_covered_rural',
            label: 'Rural population covered',
            dataType: 'PERCENTAGE',
            description: 'Share of the rural population within your network coverage.',
            unit: '%',
            isMandatory: true,
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'sites_on_air',
            label: 'Sites on air',
            dataType: 'INTEGER',
            description: 'Base stations carrying live traffic at the end of the quarter.',
            isMandatory: true,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'sites_with_backup_power',
            label: 'Sites with backup power',
            dataType: 'PERCENTAGE',
            description: 'Share of on-air sites with a generator or battery backup.',
            unit: '%',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'predominant_access_technology',
            label: 'Main access technology',
            dataType: 'REFERENCE',
            description: 'The technology that carries most of your traffic in this quarter.',
            referenceCategory: 'TECHNOLOGY',
            allowsOther: true,
          },
          {
            key: 'coverage_gis_submitted',
            label: 'Coverage map submitted with this return',
            dataType: 'BOOLEAN',
            description: 'Tick if an up to date coverage map has been attached to this return.',
          },
        ],
      },
      {
        key: 'traffic_usage',
        title: 'Traffic and usage',
        description: 'Total voice, messaging and data carried across the quarter.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'voice_minutes',
            label: 'Voice minutes',
            dataType: 'INTEGER',
            description:
              'Total billable voice minutes originated by your subscribers in the quarter.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'sms_sent',
            label: 'SMS sent',
            dataType: 'INTEGER',
            description: 'Total person to person SMS sent by your subscribers in the quarter.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'data_volume_tb',
            label: 'Data volume',
            dataType: 'DECIMAL',
            description: 'Total data carried over the mobile network in the quarter.',
            unit: 'TB',
            decimals: 2,
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'data_active_users',
            label: 'Active data users',
            dataType: 'INTEGER',
            description: 'Subscribers who used mobile data at least once in the last 90 days.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'arpu',
            label: 'Average revenue per user',
            dataType: 'MONETARY',
            description: 'Average monthly revenue per active subscriber for the quarter.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'NONE',
            minValue: 0,
          },
        ],
      },
      {
        key: 'quality_snapshot',
        title: 'Quality snapshot',
        description: 'A short view of service quality and customer complaints for the quarter.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'network_availability',
            label: 'Network availability',
            dataType: 'PERCENTAGE',
            description: 'Share of the quarter the network was available to carry traffic.',
            unit: '%',
            isMandatory: true,
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'dropped_call_rate',
            label: 'Dropped call rate',
            dataType: 'PERCENTAGE',
            description: 'Share of connected calls that dropped before the caller ended them.',
            unit: '%',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'customer_complaints',
            label: 'Customer complaints received',
            dataType: 'INTEGER',
            description: 'Complaints logged from subscribers during the quarter.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'complaints_resolved',
            label: 'Customer complaints resolved',
            dataType: 'INTEGER',
            description: 'Complaints closed during the quarter, including those carried over.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'prepared_by',
            label: 'Return prepared by',
            dataType: 'TEXT',
            description: 'Name of the officer who prepared this return.',
          },
          {
            key: 'snapshot_notes',
            label: 'Notes on service quality',
            dataType: 'TEXTAREA',
            description:
              'Anything that helps explain the quality figures, such as major incidents.',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'Prepaid and postpaid subscribers should add up to the total subscribers.',
        config: {
          operands: ['prepaid_subscribers', 'postpaid_subscribers'],
          total: 'total_subscribers',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Active subscribers cannot be more than total subscribers.',
        config: {
          left: 'active_subscribers',
          right: 'total_subscribers',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Complaints resolved cannot be more than complaints received.',
        config: {
          left: 'complaints_resolved',
          right: 'customer_complaints',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label:
          'Please check total subscribers if they have moved by more than half since last quarter.',
        config: {
          field: 'total_subscribers',
          thresholdPercent: 50,
        },
      },
    ],
  },
  {
    name: 'Voice and Interconnection Return',
    description:
      'Quarterly voice return for mobile network operators covering on-net and off-net traffic, ' +
      'national interconnection, international traffic, and wholesale minutes.',
    sections: [
      {
        key: 'onnet_offnet',
        title: 'On-net and off-net minutes',
        description:
          'Voice minutes originated by your subscribers, split by where the call terminated.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'onnet_minutes',
            label: 'On-net minutes',
            dataType: 'INTEGER',
            description: 'Minutes that started and ended on your own network.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'offnet_minutes',
            label: 'Off-net minutes',
            dataType: 'INTEGER',
            description: 'Minutes that started on your network and ended on another operator.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_originated_minutes',
            label: 'Total originated minutes',
            dataType: 'INTEGER',
            description: 'All voice minutes originated by your subscribers in the quarter.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'avg_call_duration_minutes',
            label: 'Average call length',
            dataType: 'DECIMAL',
            description: 'Average length of a connected call in the quarter.',
            unit: 'minutes',
            decimals: 2,
            flowOrStock: 'NONE',
            minValue: 0,
          },
        ],
      },
      {
        key: 'national_interconnection',
        title: 'National interconnection',
        description:
          'Traffic exchanged with other operators inside South Sudan and the money that went with it.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'incoming_interconnect_minutes',
            label: 'Incoming interconnection minutes',
            dataType: 'INTEGER',
            description:
              'Minutes received from other national operators for termination on your network.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'outgoing_interconnect_minutes',
            label: 'Outgoing interconnection minutes',
            dataType: 'INTEGER',
            description:
              'Minutes handed to other national operators for termination on their networks.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'interconnect_revenue',
            label: 'Interconnection revenue',
            dataType: 'MONETARY',
            description: 'Termination charges earned from other national operators in the quarter.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'interconnect_cost',
            label: 'Interconnection cost',
            dataType: 'MONETARY',
            description: 'Termination charges paid to other national operators in the quarter.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'international_traffic',
        title: 'International traffic',
        description: 'Voice minutes and money exchanged with carriers outside South Sudan.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'intl_incoming_minutes',
            label: 'Incoming international minutes',
            dataType: 'INTEGER',
            description: 'Minutes received from foreign carriers for termination on your network.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'intl_outgoing_minutes',
            label: 'Outgoing international minutes',
            dataType: 'INTEGER',
            description: 'Minutes sent to foreign carriers from your subscribers.',
            unit: 'minutes',
            isMandatory: true,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'intl_incoming_revenue',
            label: 'Incoming international revenue',
            dataType: 'MONETARY',
            description:
              'Revenue earned from terminating incoming international traffic in the quarter.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'intl_outgoing_cost',
            label: 'Outgoing international cost',
            dataType: 'MONETARY',
            description: 'Charges paid to foreign carriers for outgoing traffic in the quarter.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'intl_surtax_collected',
            label: 'International surtax collected',
            dataType: 'MONETARY',
            description:
              'Surtax collected on incoming international minutes and held for the Authority.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
        ],
      },
      {
        key: 'wholesale',
        title: 'Wholesale',
        description: 'Bulk minutes and capacity sold to other licensed players in the quarter.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'wholesale_minutes',
            label: 'Wholesale minutes sold',
            dataType: 'INTEGER',
            description: 'Bulk voice minutes sold to resellers and other carriers in the quarter.',
            unit: 'minutes',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'wholesale_revenue',
            label: 'Wholesale revenue',
            dataType: 'MONETARY',
            description: 'Revenue earned from wholesale minutes and capacity in the quarter.',
            unit: 'SSP',
            decimals: 2,
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'wholesale_partners',
            label: 'Number of wholesale partners',
            dataType: 'INTEGER',
            description:
              'Carriers and resellers you had a live wholesale agreement with at quarter end.',
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'capacity_leased_gbps',
            label: 'Capacity leased out',
            dataType: 'DECIMAL',
            description: 'Total transmission capacity leased to third parties at quarter end.',
            unit: 'Gbps',
            decimals: 2,
            flowOrStock: 'STOCK',
            minValue: 0,
          },
          {
            key: 'wholesale_notes',
            label: 'Notes on wholesale activity',
            dataType: 'TEXTAREA',
            description: 'Anything worth flagging about wholesale deals in the quarter.',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'SUM_EQUALS_TOTAL',
        severity: 'HARD',
        label: 'On-net and off-net minutes should add up to total originated minutes.',
        config: {
          operands: ['onnet_minutes', 'offnet_minutes'],
          total: 'total_originated_minutes',
        },
      },
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'On-net minutes cannot be more than total originated minutes.',
        config: {
          left: 'onnet_minutes',
          right: 'total_originated_minutes',
        },
      },
      {
        type: 'NONZERO_REQUIRES',
        severity: 'HARD',
        label:
          'If there are incoming international minutes, incoming international revenue is expected too.',
        config: {
          when: 'intl_incoming_minutes',
          require: 'intl_incoming_revenue',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label:
          'Please check incoming international minutes if they have moved a lot since last quarter.',
        config: {
          field: 'intl_incoming_minutes',
          thresholdPercent: 40,
        },
      },
    ],
  },
  {
    name: 'Network Quality of Service Return',
    description:
      'Quarterly quality of service return for mobile and internet operators covering voice KPIs, ' +
      'data KPIs, and network availability.',
    sections: [
      {
        key: 'voice_kpis',
        title: 'Voice KPIs',
        description: 'Headline voice quality measures for the reporting period.',
        applicableEntityTypes: ['MNO'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'call_setup_success_rate',
            label: 'Call setup success rate',
            dataType: 'PERCENTAGE',
            description: 'Share of call attempts that connected successfully.',
            unit: '%',
            isMandatory: true,
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'dropped_call_rate',
            label: 'Dropped call rate',
            dataType: 'PERCENTAGE',
            description: 'Share of connected calls that dropped before the caller ended them.',
            unit: '%',
            isMandatory: true,
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'call_completion_rate',
            label: 'Call completion rate',
            dataType: 'PERCENTAGE',
            description: 'Share of call attempts that both connected and ended normally.',
            unit: '%',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'measurement_period_start',
            label: 'Measurement start date',
            dataType: 'DATE',
            description: 'The first day of the measurement window these voice figures cover.',
            isMandatory: true,
          },
        ],
      },
      {
        key: 'data_kpis',
        title: 'Data KPIs',
        description: 'Headline data quality measures from network counters and drive tests.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'avg_download_mbps',
            label: 'Average download speed',
            dataType: 'DECIMAL',
            description: 'Average download throughput seen by customers in the period.',
            unit: 'Mbps',
            decimals: 2,
            isMandatory: true,
            minValue: 0,
          },
          {
            key: 'avg_upload_mbps',
            label: 'Average upload speed',
            dataType: 'DECIMAL',
            description: 'Average upload throughput seen by customers in the period.',
            unit: 'Mbps',
            decimals: 2,
            minValue: 0,
          },
          {
            key: 'avg_latency_ms',
            label: 'Average latency',
            dataType: 'INTEGER',
            description: 'Average round trip time measured to a national reference point.',
            unit: 'ms',
            minValue: 0,
          },
          {
            key: 'packet_loss_rate',
            label: 'Packet loss rate',
            dataType: 'PERCENTAGE',
            description: 'Share of packets lost in the measurement window.',
            unit: '%',
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'drive_test_completed',
            label: 'Drive test carried out this period',
            dataType: 'BOOLEAN',
            description: 'Tick if a drive test backed up these data figures.',
          },
        ],
      },
      {
        key: 'network_availability',
        title: 'Network availability',
        description: 'Uptime and outages across the network for the reporting period.',
        applicableEntityTypes: ['MNO', 'ISP'],
        frequency: 'QUARTERLY',
        fields: [
          {
            key: 'network_uptime',
            label: 'Network uptime',
            dataType: 'PERCENTAGE',
            description: 'Share of the period the network was available to carry traffic.',
            unit: '%',
            isMandatory: true,
            minValue: 0,
            maxValue: 100,
          },
          {
            key: 'outages_count',
            label: 'Number of outages',
            dataType: 'INTEGER',
            description: 'Count of service affecting outages in the period.',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'total_outage_minutes',
            label: 'Total outage minutes',
            dataType: 'INTEGER',
            description: 'Total minutes of service affecting outage across the period.',
            unit: 'minutes',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'planned_outage_minutes',
            label: 'Planned outage minutes',
            dataType: 'INTEGER',
            description: 'Minutes of outage that came from planned maintenance.',
            unit: 'minutes',
            flowOrStock: 'FLOW_ENTERED',
            minValue: 0,
          },
          {
            key: 'avg_restoration_time_minutes',
            label: 'Average restoration time',
            dataType: 'DECIMAL',
            description: 'Average time taken to restore service after an outage.',
            unit: 'minutes',
            decimals: 1,
            flowOrStock: 'NONE',
            minValue: 0,
          },
          {
            key: 'availability_notes',
            label: 'Notes on outages',
            dataType: 'TEXTAREA',
            description: 'Short account of the main outages and what caused them.',
          },
        ],
      },
    ],
    rules: [
      {
        type: 'LESS_OR_EQUAL',
        severity: 'HARD',
        label: 'Planned outage minutes cannot be more than total outage minutes.',
        config: {
          left: 'planned_outage_minutes',
          right: 'total_outage_minutes',
        },
      },
      {
        type: 'NONZERO_REQUIRES',
        severity: 'HARD',
        label: 'If any outages are reported, total outage minutes should be filled in as well.',
        config: {
          when: 'outages_count',
          require: 'total_outage_minutes',
        },
      },
      {
        type: 'PERIOD_ON_PERIOD',
        severity: 'SOFT',
        label: 'Please check the number of outages if it has jumped since last quarter.',
        config: {
          field: 'outages_count',
          thresholdPercent: 50,
        },
      },
    ],
  },
];
